name: "hello docker github"
description: "the first action test"
inputs:
    who-to-greet:
        description: "who to greet"
        required: true
        default: "World"
outputs:
    time:
        description: "that time we greet you"


run:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.who-to-greet }}
